"""Internal layout types for grounded document parsing.

These types validate the parser's block geometry and JSON artifact. They are
not a user-defined field extraction schema.

Must not: give any of these models a field with a Python default (breaks
OpenAI's strict json_schema mode -- see the comment block below and
docs/MODEL.md) or a fixed-length tuple type.

Next: src/parse.py for how these types are populated.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator
from src.diagnostics import PageDiagnostic

# OpenAI's structured-outputs strict mode (with_structured_output(..., method="json_schema"))
# requires every property in `required` (no field may rely on a Python default to be
# "optional" -- use a nullable type instead) and does not support fixed-length tuple
# validation (`prefixItems`, generated by e.g. tuple[float, float, float, float]). Every
# model sent to the model is shaped to satisfy both constraints; see docs/MODEL.md.


def _require_xyxy_len(v: tuple[float, ...]) -> tuple[float, ...]:
    if len(v) != 4:
        raise ValueError("xyxy must have exactly 4 values (x0, y0, x1, y1)")
    return v


class BBox(BaseModel):
    model_config = ConfigDict(extra="forbid")

    page: int  # 1-based
    xyxy: tuple[float, ...]  # normalized 0-1, exactly 4 values (x0, y0, x1, y1)

    _check_xyxy = field_validator("xyxy")(_require_xyxy_len)


class ParseBlock(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    type: Literal[
        "title", "heading", "text", "list", "table", "key_value", "figure", "marginalia", "other"
    ]
    text: str
    bbox: BBox | None
    conf: float | None
    table: list[list[str]] | None  # rows, only when type == "table"

    @field_validator("table")
    @classmethod
    def _rectangularize_table(cls, value: list[list[str]] | None) -> list[list[str]] | None:
        """Preserve cells while padding omitted trailing blanks in model output."""
        if not value:
            return value
        width = max(len(row) for row in value)
        return [row + [""] * (width - len(row)) for row in value]


class ParsePage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    page: int
    width_px: int
    height_px: int
    blocks: list[ParseBlock]


class ParseResult(BaseModel):
    model_config = ConfigDict(extra="forbid")

    doc_sha: str
    pages: list[ParsePage]
    content_filtered_pages: list[int] = Field(default_factory=list)
    page_diagnostics: list[PageDiagnostic] = Field(default_factory=list)
    model: str = "gpt-6-sol"
