"""Pydantic schemas for every payload that crosses the model boundary: the
active `ParsePage`/`ParseBlock`/`ParseResult` layout schema, plus the
dormant `Invoice`/`LineItem`/`Region`/`ValidationReport` invoice schemas
(see docs/ARCHITECTURE.md). A model response only becomes trusted data after
it validates against one of these -- see src/extract.py's
`_invoke_structured`, which is the only place that happens, and
src/validate.py for the *arithmetic* checks a valid `Invoice` still needs
before it's trustworthy.

Must not: give any of these models a field with a Python default (breaks
OpenAI's strict json_schema mode -- see the comment block below and
docs/MODEL.md) or a fixed-length tuple type.

Next: src/parse.py (active) or src/validate.py (dormant) for how these
schemas get populated and checked.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator
from src.diagnostics import PageDiagnostic

# OpenAI's structured-outputs strict mode (with_structured_output(..., method="json_schema"))
# requires every property in `required` (no field may rely on a Python default to be
# "optional" -- use a nullable type instead) and does not support fixed-length tuple
# validation (`prefixItems`, generated by e.g. tuple[float, float, float, float]). Every
# model below that gets sent to the model as a structured-output schema (Invoice, Region,
# BBox, ParseBlock/ParsePage) is shaped to satisfy both constraints; see docs/MODEL.md.


def _require_xyxy_len(v: tuple[float, ...]) -> tuple[float, ...]:
    if len(v) != 4:
        raise ValueError("xyxy must have exactly 4 values (x0, y0, x1, y1)")
    return v


class LineItem(BaseModel):
    model_config = ConfigDict(extra="forbid")

    description: str
    quantity: float
    unit_price: float
    amount: float


class Invoice(BaseModel):
    model_config = ConfigDict(extra="forbid")

    invoice_number: str
    vendor: str | None
    invoice_date: str | None
    currency: str | None
    line_items: list[LineItem]
    subtotal: float
    tax: float
    grand_total: float


class Region(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    field_or_line_index: str
    conf: float
    bbox_xyxy: tuple[float, ...]  # normalized 0-1, exactly 4 values (x0, y0, x1, y1)
    reason: str | None

    _check_bbox_xyxy = field_validator("bbox_xyxy")(_require_xyxy_len)


class ValidationErrorItem(BaseModel):
    model_config = ConfigDict(extra="forbid")

    code: str
    msg: str
    expected: float | None = None
    actual: float | None = None


class ValidationReport(BaseModel):
    model_config = ConfigDict(extra="forbid")

    ok: bool
    errors: list[ValidationErrorItem]


class BBox(BaseModel):
    model_config = ConfigDict(extra="forbid")

    page: int  # 1-based
    xyxy: tuple[float, ...]  # normalized 0-1, exactly 4 values (x0, y0, x1, y1)

    _check_xyxy = field_validator("xyxy")(_require_xyxy_len)


class ParseBlock(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    type: Literal[
        "title", "heading", "text", "table", "key_value", "figure", "line_item", "other"
    ]
    text: str
    bbox: BBox | None
    conf: float | None
    table: list[list[str]] | None  # rows, only when type == "table"


class ParsePage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    page: int
    width_px: int
    height_px: int
    blocks: list[ParseBlock]


class ParseResult(BaseModel):
    model_config = ConfigDict(extra="forbid")

    doc_sha: str
    pages: list[ParsePage]
    content_filtered_pages: list[int] = Field(default_factory=list)
    page_diagnostics: list[PageDiagnostic] = Field(default_factory=list)
    model: str = "gpt-6-sol"
